server:
  port: 8088

spring:
  datasource :
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  message:
    basename: messages

#  security:
#    user:
#      name: username
#      password: passw0rd

#logging:
#  level:
#    org.springframework: debug